### ISSUE TITLE
RethinkDB's company closed , are there alternatives?

### ISSUE THREAD

**Issue by marcoalbarelli** [grantcarthew/node-rethinkdb-job-queue#22]
https://rethinkdb.com/blog/rethinkdb-shutdown/

My impression is that rethinkdb is just too godd to end up like this.
Most likely some company/foundation will show up and pick it up
Not a good news though ...

**Comment by grantcarthew** [comment]
This will not be the end.

Search for `database` on the front page of github and you get this:
Redis: `20000` Stars
RethinkDB: `16000`
MongoDB: `10000`

Some other popular project as a reference:
Aurelia: `8000`
Angular: `17000`
Node.js: `27000`
Sailsjs: `15000`
Express: `27000`

I have used MongoDB, RethinkDB is streets ahead. MongoDB was just the first and because of that it ended up being the database for projects like `sailsjs` and many others.

Someone will have to run with this. It is being discussed here:
https://github.com/rethinkdb/rethinkdb/issues/6137

Although, this could just be wishful thinking considering I have spent the last five months of my free time working on this job queue.

**Comment by thomasmodeneis** [comment]
I loved this queue, but the fact that rethink is shutting down is scary. :(

**Comment by grantcarthew** [comment]
@thomasmodeneis It's not shutting down, the business behind it has shut down.

Read here: https://rethinkdb.slack.com/messages/open-rethinkdb/
And here: https://docs.google.com/document/d/1Fy-drBGDTyibwEBBAX6G5otqtWiKOD2sBXmL2uVTFtE/edit

**Comment by grantcarthew** [comment]
More:
https://www.compose.com/articles/rethinkdb-and-compose-where-next/

**Comment by thomasmodeneis** [comment]
So far so good, besides not having reliable changefeeds, there is not much more to worry, so far so good.
Thanks for the headsup :)
Cheers.

**Comment by grantcarthew** [comment]
RethinkDB has Joined the Linux Foundation. See #50 for more detail.
