### ISSUE TITLE
Should setProgress automatically log change?

### ISSUE THREAD

**Issue by TomKaltz** [grantcarthew/node-rethinkdb-job-queue#29]
Should job.setProgress() automatically add a log entry just like the new job.update() functionality?

Should all the job.set*****() methods automatically log the change?

**Comment by grantcarthew** [comment]
@TomKaltz, you are good at finding nooks and crannies in the project.

Your question prompted me to review the methods. In hind sight, I should change the name of `Job.setProgress` to `Job.updateProgress`.

The other set methods are simply changing the properties of the Job, not touching the database. `Job.setProgress` is the only method that changes the database.

I have created a Project and am adding items that should be reviewed for v2.0.
https://github.com/grantcarthew/node-rethinkdb-job-queue/projects/1

Feel free to add to it. I'll close this for now due to the project.

**Comment by grantcarthew** [comment]
@TomKaltz, Just found out you can't add to projects.
Raise new issues if you have any more ideas.

Thanks.

**Comment by grantcarthew** [comment]
Hi @TomKaltz, I just published v1.0.2 which includes automatic logs for `Job.setProgress` however I will not rename until v2.
