### ISSUE TITLE
Enqueuing jobs straight from Horizon

### ISSUE THREAD

**Issue by tailsu** [grantcarthew/node-rethinkdb-job-queue#30]
I'd like to have the functionality of `createJob/addJob` client-side using Horizon. I imagine that I can use the information from the Job Schema wiki article, build a Job object and push it straight into the queue table with a Horizon query.

Do you see anything wrong with this approach? Which of the job properties are required and which are filled in later by the processor?

Ideally, I'd like to see the `createJob/addJob` pair provided as a separate module that integrates with a horizon client.

**Comment by grantcarthew** [comment]
Hi @tailsu. Do you write back-end code at all? This is typically the type of thing you do on the server side. Build an API that takes the data, and then add the job behind the API.

I don't know Horizon very well so I may be misunderstanding how it fits into the picture.

**Comment by tailsu** [comment]
Horizon lets you access RethinkDB and its **changefeeds** straight from a web app.

So, I'm building a scalable web app that has (among other things) a video processing service and I also want to show the progress of running video operations to users. Kind of like the Youtube upload works. I figure that the web app can post video processing jobs straight to the queue using Horizon, and again using Horizon, get progress reports on the video job from the queue changefeed.

My back-end is very minimal - only login and file upload is handled through a traditional API, everything else in it is built around Horizon.

**Comment by marcoalbarelli** [comment]
I still havent't had the time to play around with horizon, I plan to use it for an upcoming small project
Anyhow since updating a job triggers an update I think what you want to do is possible

I take it you have to listen on Rethink changefeed on your own, so you also have to parse raw rethinkdb results into valid jobs, but this is quite easy (take a look at the job class constructor)

**Comment by grantcarthew** [comment]
I'm not really understanding how this fits together @tailsu.
Are you saying you install the `rethinkdb-job-queue` module on the server or are you trying to run it on the client. If you are installing it on the server you would still need to manage an API to receive jobs.

This is my problem. I just don't fully understand.

**Comment by tailsu** [comment]
The server runs a queue processor that's connected to a RethinkDB. The queue processor  gets video processing requests and returns its results through the job log. Nothing weird going on here.

The jobs themselves are requested by the client, a web app. For example - the client has uploaded a video and wants to crop it. The client uses Horizon to write directly into the queue table a cropping job, with a link to the video and the job parameters. The client then listens to the queue changefeed to get progress reports on the job and finally reads the result from the job's log.

With a traditional API, I would create an API WebSocket endpoint for cropping jobs. A request to it would:
* open a WS
* read the job parameters
* use the `createJob/addJob` API to start the job
* listen on the queue for progress and completion events and pass that information over the websocket to the client.

Because Horizon already does that - it already provides a WebSocket for real-time communication, I don't need a middleman here. I can go from the client straight to the queue table and order my burger and fries there.

BTW, I've found through trial and error that something to this vibe works in the browser:

```js
export async function runJob(queue, payload) {
    let jobId = uuid.v4();
    let job = {
        id: jobId,
        dateCreated: new Date(),
        dateEnable: new Date(),
        log: [],
        priority: 40,
        queueId: 'doesnt matter',
        retryCount: 0,
        retryDelay: 100000,
        retryMax: 0,
        status: 'waiting',
        timeout: 100000,
        request: payload,
    }
    await horizon(queue).upsert(job);
    let subscription;
    try {
        return await new Promise((resolve, reject) => {
            subscription = horizon(queue).find({id: jobId}).watch().subscribe(job => {
                if (!job) {
                    return;
                }
                let {status} = job; 
                if (status === 'active' || status === 'waiting') {
                    return;
                }
                
                if (status !== 'completed') {
                    reject(Error(status));
                    return;
                }

                let details = _.find(job.log, entry => entry.status === 'completed');
                resolve(details.data);
                horizon(queue).remove(jobId);
            }, reject);
        });
    } finally {
        if (subscription) {
            subscription.unsubscribe();
        }
    }
}
```

On the server I have just this:
```js
    const q = new Queue({
       // ....
    }, {
        name: 'asset_conversions',
        changeFeed: true,
        concurrency: 2,
        removeFinishedJobs: 3600*1000,
    });

    q.process((job, next) =>
        convertAsset(job.request).then(next).catch(next)
    );
```

The request is passed through a `request` field on the job and the response is read from the job log.

**Comment by tailsu** [comment]
OK, so question is: is it okay to do things like this? Will something break? Do I depend too much on implementation details.

I do foresee a nice NPM module, say `horizon-job-queue` with the above code included.

Thoughts?

**Comment by grantcarthew** [comment]
Right, I understand now.

It must be a limitation in Horizon because the correct approach in this case, I think, would be to build the job adding functionality into an API call like `/jobs/add` and pass in just the job data.

I see nothing wrong with adding the JSON data directly into the database. The `status` of the job will need to be `waiting` as you have done above. Also the other properties would need to be populated, as you have done.

Getting the change feed right will be up to you though. When I built `rethinkdb-job-queue` I decided to set the change feed on the whole table and then parse the changes locally. See this module to better understand the design: https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/src/queue-change.js

In your case, you may want to make the change feed query more targeted.

From an architecture point of view, the queue table is the heart of the queue. The worker Queue objects find jobs that need processing and process them. It should work fine.

It still feels a bit backward though.

**Comment by tailsu** [comment]
OK, gotcha.

Backward or not, you just can't get a changefeed out of a REST endpoint.
