### ISSUE TITLE
Should global queue state documents be held in a specific queue state table?

### ISSUE THREAD

**Issue by TomKaltz** [grantcarthew/node-rethinkdb-job-queue#36]
Should queue state documents be held in a specific table?  This way you can index on queue name and not hard-code the document id.  Also, if someone does ```delete()``` on a queue/table then the worker processes will lose changefeed to the state document and subsequent reviews will not trigger queue processing.  Could be avoided if the state document is held in it's own table.

**Comment by TomKaltz** [comment]
PK can be the queue name to restrict duplicates.  Is there a big reason to keep this document in the individual queue table?  The hard-coded uuid seems like a dirty hack.

**Comment by grantcarthew** [comment]
All valid concerns @TomKaltz, however they are all irrelevant.

The Queue object change feed is for the whole queue table, not the state document. Change events are processed within the Queue object.

If I didn't have a fixed id on the state document, then I would need to put an identity hash or field on the state document. Why do that when you can use the id?

The state document is never read. It is only ever written to.

The state document write module is using an `insert` statement with a ` { conflict: 'replace' }` option. This means it will create the document if it does not exist, and if it does it replaces the current document.

State document deletions are ignored.

Read more here: https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/src/queue-state.js
And here: https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/src/queue-change.js

Nice work though @TomKaltz, keep it up. You have found a few design issues since you started pocking around. Keep on poking.
