### ISSUE TITLE
In distributed mode, won't the changefeed send jobs to all the queues?

### ISSUE THREAD

**Issue by HardlyMirage** [grantcarthew/node-rethinkdb-job-queue#5]
I was thinking about implementing this job queue for one of my video processing projects, but had a question. I read the wiki and wasn't able to find any info on how queues are handled in a distributed environment.

If I have multiple subscribers running on different servers, won't the changefeed send the jobs to each of them? I don't see the module setting `write_acks`, `durability` or `read_mode` settings to the table anywhere.

**Comment by grantcarthew** [comment]
Hi @HardlyMirage,

I haven't done any performance testing of the queue and would be rather surprised if it was on par with the other queue solutions. I didn't really make `rethinkdb-job-queue` to be the fastest.

With that in mind I decided to leave the RethinkDB options at there default because it gives a good [consistency guarantee](https://www.rethinkdb.com/docs/consistency/). The best consistency would be to set `read_mode` to majority.

With regards to the `changeFeed` option, if you set it to false, the local Queue object will only raise local events.

Read more about distributed processing, events, and change feed on these documents.
https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-Events
https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-PubSub

What's your opinion on the `read_mode`?

**Comment by TomKaltz** [comment]
I think the question was regarding multiple discrete job processors and how locking is handled so that two processed don't end up picking up the same job at the same time.

**Comment by grantcarthew** [comment]
Ah, if what @TomKaltz is saying is correct, that issue is avoided by the RethinkDB queries used to retrieve the jobs. They are atomic operations. When the job is retrieved its status is set to `active` preventing other Queue objects retrieving the job.

Have a look at this file and the query it contains. It should clear any confusion.
https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/src/queue-get-next-job.js

Note that the `getNextJob()` function in that file is using this index.
https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/404c75851003ebe13cc409e77bd23fce2e25d19c/src/db-assert-index.js#L26
The `indexInactivePriorityDateCreated` index will only retrieve `active` jobs.

Still not sure if `read_mode` should be set to majority though.

**Comment by HardlyMirage** [comment]
@TomKaltz is right, that was indeed my concern.

I still think we should set `read_mode` to majority. Or at least, expose those options to allow developers to configure them.

I've tested the queue subscriptions with changefeeds on two servers concurrently and the jobs are not overlapping. So I don't think this is an issue.

Btw, OT, I love the documentation for this project, apart from everything else. Great work!
