### ISSUE TITLE
Job to Job Queue?

### ISSUE THREAD

**Issue by chrisabrams** [grantcarthew/node-rethinkdb-job-queue#56]
I was curious about the best way to approach the following:

I have Job A.
I have Job B.

I would like Job B to run once Job A has successfully completed. Optionally, I would like to pass the `job.data` from Job A to Job B. Ideally, Job A would not need to know about Job B.

**Comment by grantcarthew** [comment]
Hi Chris,
Have a read of this: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Complex-Job

That is a general look at complex jobs. In your case I see two options:

1.   Instead of Job A and Job B, just have Job with the data to process within.
2.   Use two queues. When Job A is complete add Job B to the second queue.

Both of these answers need Job A to know about Job B though.

The other option is to build complex job processing into Job B so that when Job B is processed it looks for the `name` of job A, if Job A is complete start processing Job B.

You could also add `completed` event processing so when Job A is processed Job B gets added to the queue.

I would need more detail on the Jobs to expand on this. Just trying to give you ideas.

**Comment by chrisabrams** [comment]
I think the completed event would work best. To give you an idea:

Job A could be a pdf is uploaded.
Job B could be an image is captured of the pdf to serve as a thumbnail.

There are times where Job B is not required, so that's why making Job A not aware of B is ideal. However, with the complete event, I think I'll do the higher level job approach, and that job will determine whether Job B needs to wait on the completion of Job A.

I'll try this route and let you know how it goes.

**Comment by grantcarthew** [comment]
Ah, so you will have three queues?
1.   NewUpload
2.   UploadFile
3.   CreateThumbnail

And in this case the job in NewUpload will manage the other two queues?

I'm interested in what you come up with. Let me know.

You just made me realize a change I should have added when the `name` feature was added. The events should include the job name.   Maybe next time.
