### ISSUE TITLE
Problem if multiple worker and using q.on('progress', ...)

### ISSUE THREAD

**Issue by gkumar9** [grantcarthew/node-rethinkdb-job-queue#84]
While having Multiple worker, if i use q.on('progress',..) the other worker also, responds. Why?
My code:
Process.js
```
const Queue = require('rethinkdb-job-queue')
const qOptions = {
    name: 'Mathematics' // The queue and table name
}
const cxnOptions = {
    db: 'JobQueue', // The name of the database in RethinkDB
}

const q = new Queue(cxnOptions, qOptions)

function getJobs() {
    q.process((job, next) => {
        
        try {
            let result = job.numerator / job.denominator
            console.log('result', result);
            // Do something with your result
            return next(null, result)
        } catch (err) {
            console.error(err)
            return next(err)
        }
    })
    q.on('completed', async(queueId, jobId, isRepeating) => {
        // console.log('Processing Queue: ' + queueId)
        
            console.log('Job completed: ' + jobId)

    })
    q.on('progress', async(queueId, jobId, percent) => {

        console.log('Job progress: ' + percent)
           
    })
}
getJobs()
```
Create.js
```
const Queue = require('rethinkdb-job-queue')
const qOptions = {
    name: 'Mathematics' // The queue and table name
}
const cxnOptions = {
    db: 'JobQueue', // The name of the database in RethinkDB
}

const q = new Queue(cxnOptions, qOptions)

const job = q.createJob({
    numerator: 123,
    denominator: 456
})

return q.addJob(job).catch((err) => {
    console.error(err)
})
```
Screeshot of output.
![worker2](https://user-images.githubusercontent.com/33317261/42504451-7c8e7684-8459-11e8-83e6-d59a95d52e1b.png)

**Comment by grantcarthew** [comment]
Hi @gkumar9 

As you can see here: https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/ae3111cdd7596c552e05d60a32daadd4088af63f/src/job-completed.js#L13

When a job is complete its progress gets set to 100%.

If you are only interested in progress reports for local jobs, just filter by the job ids in your worker.

**Comment by gkumar9** [comment]
@grantcarthew 
Thats fine, but the problem is as below :
I have 3 workers (worker1, worker2, worker3) running simultaneously waiting for the job to be added inside the queue.

The job is added through create.js
All workers (worker1, worker2, worker3) (named as process.js inside screenshot above) having identical code and containing q.on('progress') and q.on('completed')

What my understanding is, as the job is added, only one of the worker (i.e., worker1) should start running job and that same worker should only respond to progress and completed events. 

But as you can see in the screenshot, the other 2 workers (worker2, worker3) are giving the response of progress. This is misleading.


Can you please explain this scenario.
Thanks

**Comment by grantcarthew** [comment]
This is all documented @gkumar9 

Start here: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-Events

More here: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-PubSub#subscriber-queue-object

Finish here: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-Options#queue-changefeed-option

To summarize the above:

* Change feed enabled will cause the Queue object to receive events for the whole queue.
* Change feed disabled will cause the Queue object to not respond to jobs added to the queue by other publishers. It will only work with jobs added to the queue by its self (and jobs found after adding a job).
* The subscribers do not poll the database, the only way they receive updates is by the change feed.
* The Master Queue is an exception to the above rule.

You have two options:

* Unlike your above event handler code which is ignoring the jobId, use it to filter events to locally processed jobs.
* Construct your own change feed for the subscriber that filters for the jobId. 

The second option is not difficult however I would suggest the top option to be a better one.

Something like this (pay attention to the `jobIdCache` variable):

```js

const Queue = require('rethinkdb-job-queue')
const qOptions = {
    name: 'Mathematics' // The queue and table name
}
const cxnOptions = {
    db: 'JobQueue', // The name of the database in RethinkDB
}
const jobIdCache = new Set()

const q = new Queue(cxnOptions, qOptions)

function getJobs() {
    q.process((job, next) => {
        jobIdCache.add(job.id)
        try {
            let result = job.numerator / job.denominator
            console.log('result', result);
            // Do something with your result
            return next(null, result)
        } catch (err) {
            jobIdCache.delete(job.id)
            console.error(err)
            return next(err)
        }
    })
    q.on('completed', async(queueId, jobId, isRepeating) => {
        // console.log('Processing Queue: ' + queueId)
        if (jobIdCache.has(jobId)) {
            console.log('Job completed: ' + jobId)
            jobIdCache.delete(jobId)
        }
    })
    q.on('progress', async(queueId, jobId, percent) => {

        console.log('Job progress: ' + percent)
           
    })
}
getJobs()

```

This is a silly example of a process handler because it is not asynchronous so the job is complete as soon as you call next in the handler. It does the job for a description though.

**Comment by grantcarthew** [comment]
Closing this @gkumar9 as is it documented and you are not responding.
